[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "luminide"
authors = [{name = "Luke", email = "luke@luminide.com"}]
dynamic = ["version", "description"]
